import type { Metadata } from "next";
import GlobalStyle from "@/style/globalStyle";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
