import { random } from "lodash";

export type AreaElectData = {
  id: number;
  name: string;
  intall: number;
  electric: number;
  top: string;
  bottom: string;
  left: string;
  right: string;
  status: number;
};

// const temp =[
//       {
//         id: 0,
//         name: "단북면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "500px",
//         bottom: "",
//         left: "-50px",
//         right: "",
//         status: random(0, 2),
//       },
//       {
//         id: 1,
//         name: "단밀면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "550px",
//         left: "-90px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 2,
//         name: "구천면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "300px",
//         left: "200px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 3,
//         name: "비안면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "420px",
//         left: "620px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 4,
//         name: "봉양면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "150px",
//         left: "850px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 5,
//         name: "금성면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "50px",
//         left: "1300px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 6,
//         name: "가음면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "-10px",
//         left: "",
//         right: "1450px",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 7,
//         name: "춘산면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "180px",
//         left: "",
//         right: "1100px",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 8,
//         name: "사곡면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "",
//         bottom: "450px",
//         left: "",
//         right: "1230px",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 9,
//         name: "옥산면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "520px",
//         bottom: "",
//         left: "",
//         right: "1140px",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 10,
//         name: "점곡면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "250px",
//         bottom: "",
//         left: "1900px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 11,
//         name: "단순면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "200px",
//         bottom: "",
//         left: "1500px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 12,
//         name: "안평면",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "400px",
//         bottom: "",
//         left: "900px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//       {
//         id: 13,
//         name: "의성읍",
//         intall: random(0, 100),
//         electric: parseFloat(random(0, 255, true).toFixed(2)),
//         top: "800px",
//         bottom: "",
//         left: "1100px",
//         right: "",
//         status: 0, //random(0, 2),
//       },
//     ];

export const MappingData: AreaElectData[] = [
  {
    id: 0,
    name: "단북면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "500px",
    bottom: "",
    left: "-50px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 1,
    name: "단밀면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "550px",
    left: "-90px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 2,
    name: "구천면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "300px",
    left: "200px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 3,
    name: "비안면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "420px",
    left: "620px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 4,
    name: "봉양면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "150px",
    left: "850px",
    right: "",
    status: 2,
  },
  {
    id: 5,
    name: "금성면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "50px",
    left: "1300px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 6,
    name: "가음면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "-10px",
    left: "",
    right: "1450px",
    status: random(0, 2),
  },
  {
    id: 7,
    name: "춘산면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "180px",
    left: "",
    right: "1100px",
    status: random(0, 2),
  },
  {
    id: 8,
    name: "사곡면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "",
    bottom: "450px",
    left: "",
    right: "1230px",
    status: random(0, 2),
  },
  {
    id: 9,
    name: "옥산면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "520px",
    bottom: "",
    left: "",
    right: "1140px",
    status: random(0, 2),
  },
  {
    id: 10,
    name: "점곡면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "250px",
    bottom: "",
    left: "1900px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 11,
    name: "단순면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "200px",
    bottom: "",
    left: "1500px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 12,
    name: "안평면",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "400px",
    bottom: "",
    left: "900px",
    right: "",
    status: random(0, 2),
  },
  {
    id: 13,
    name: "의성읍",
    intall: random(0, 100),
    electric: parseFloat(random(0, 255, true).toFixed(2)),
    top: "800px",
    bottom: "",
    left: "1100px",
    right: "",
    status: random(0, 2),
  },
];
